language: go
  
go:
  - 1.8.x
  - 1.9.x

services:
  - mysql
  - postgresql
  
before_install:
  - mysql -e 'CREATE DATABASE date_test;'
  - psql -c 'CREATE DATABASE date_test;' -U postgres

before_script:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/lib/pq
  - go get github.com/mattn/go-sqlite3

script:
  - go test -v -cover .