language: go
  
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

services:
  - mysql
  - postgresql
  
before_install:
  - mysql -e 'CREATE DATABASE date_test;'
  - psql -c 'CREATE DATABASE date_test;' -U postgres

script:
  - go test -v -cover .
